name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 16.170.205.22
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/ubuntu"

      - name: Move files to web folder
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 16.170.205.22
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/* /var/www/html/